### ISSUE TITLE
Unable to build: missing nuget packages

### ISSUE THREAD

**Issue by sgisbert** [Sitecore/Solr.SupportPackage#1]
Hi,

I'm trying to build this package to setup Solr in a Sitecore 8.2 - update 2 instance, but I'm unable to build.

First, I had to manually setup the Sitecore nuget repos. Then, it fails because the package
<package id="Sitecore.ContentSearch.API.Solr" version="8.2.1.37-r160906" /> is missing from both Sitecore repos and the local packages folder.

May you provide this package? 

According to this page, [Configuring_an_IOC](https://doc.sitecore.net/sitecore_experience_platform/setting_up_and_maintaining/search_and_indexing/walkthrough_setting_up_solr#_Configuring_an_IOC), I have to use this package instead of the provided with the initial release of 8.2 (in the Additional tools section).

Thanks,
Sergi

**Comment by jasongm86** [comment]
Same issue here unfortunately. Mid-upgrade to Sitecore 8.2 and I can get it running until this builds. Any chance of a resolution?

Thanks,
Jason.

**Comment by kaalen** [comment]
Yep, same problem here.

**Comment by richardhauer** [comment]
I wanted to build an adapter for a new IoC but this repo isn't even close to building.  I've spent half an hour trying to get it to work, manually hunting down packages and files.  Please fix.

**Comment by Gabilin** [comment]
Resolved, sorry for taking it so long
