### ISSUE TITLE
SolrNet.0.4.0.2002 NuGet package not found...

### ISSUE THREAD

**Issue by ghost** [Sitecore/Solr.SupportPackage#5]
When I clone the repo and build I get the following message for all projects. It looks like a reference is made that doesn't exist?

NuGet Package restore failed for project Sitecore.ContentSearch.SolrProvider.CastleWindsor: Unable to find version '0.4.0.2002' of package 'SolrNet'.
https://api.nuget.org/v3/index.json: Package 'SolrNet.0.4.0.2002' is not found on source 'https://api.nuget.org/v3/index.json'.
https://sitecore.myget.org/F/sc-packages/api/v3/index.json: Package 'SolrNet.0.4.0.2002' is not found on source 'https://sitecore.myget.org/F/sc-packages/api/v3/index.json'.

**Comment by Gabilin** [comment]
Fixed by adding the needed SolrNet version to the repo. The project is using an old version of the SolrNet that is delisted from the nuget.org
