### ISSUE TITLE
After copying the output folder files getting error like Value cannot be null. Parameter name: fieldNameTranslator 

### ISSUE THREAD

**Issue by Sivalingaamorthy** [Sitecore/Solr.SupportPackage#7]
After copying the *solr* files from the output folder, getting error when opening the Content Editor.

> 
> Value cannot be null.
> Parameter name: fieldNameTranslator 
> Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 
> 
> Exception Details: System.ArgumentNullException: Value cannot be null.
> Parameter name: fieldNameTranslator
> 
> Source Error: 
> 
> An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.  
> 
> Stack Trace: 
> 
> 
> [ArgumentNullException: Value cannot be null.
> Parameter name: fieldNameTranslator]
>    Sitecore.ContentSearch.Linq.Solr.SolrIndexParameters..ctor(IIndexValueFormatter valueFormatter, IFieldQueryTranslatorMap`1 fieldQueryTranslators, FieldNameTranslator fieldNameTranslator, IExecutionContext[] executionContexts, IFieldMapReaders fieldMap, Boolean convertQueryDatesToUtc) +315
>    Sitecore.ContentSearch.SolrProvider.LinqToSolrIndex`1..ctor(SolrSearchContext context, IExecutionContext[] executionContexts) +188
>    Sitecore.ContentSearch.SolrProvider.SolrSearchContext.GetQueryable(IExecutionContext[] executionContexts) +268
>    Sitecore.Social.Search.SearchProvider.SearchItems(Expression`1 whereExpression, Func`2 selector) +165
>    Sitecore.Social.Search.SearchProvider.GetMessagesByContainer(String container) +503
>    Sitecore.Social.MessageBusinessManager.SearchMessagesByContainer(String container) +203
>    Sitecore.Social.MessageBusinessManager.GetMessagesCount(String container) +16
>    Sitecore.Social.Client.MessagePosting.Commands.SocialCenter.RunGetHeader(CommandContext context, String header) +342
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.FillParamsFromCommand(CommandContext commandContext, RibbonCommandParams ribbonCommandParams) +94
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.GetCommandParameters(Item controlItem, CommandContext commandContext) +79
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderLargeButton(HtmlTextWriter output, Item button, CommandContext commandContext) +78
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderButton(HtmlTextWriter output, Item button, CommandContext commandContext) +440
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderChunk(HtmlTextWriter output, Item chunk, CommandContext commandContext) +343
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderChunk(HtmlTextWriter output, Item chunk, CommandContext commandContext, Boolean isContextual, String id) +244
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderChunk(HtmlTextWriter output, Item chunk, CommandContext commandContext, Boolean isContextual) +161
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderChunks(HtmlTextWriter output, Item strip, CommandContext commandContext, Boolean isContextual) +449
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderStrips(HtmlTextWriter output, Item ribbon, Boolean isContextual, ListString visibleStripList) +1807
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.RenderStrips(HtmlTextWriter output, Item defaultRibbon, Item contextualRibbon, ListString visibleStripList) +162
>    Sitecore.Web.UI.WebControls.Ribbons.Ribbon.Render(HtmlTextWriter output) +800
>    System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter) +80
>    Sitecore.Web.HtmlUtil.RenderControl(Control ctl) +80
>    Sitecore.Shell.Applications.ContentManager.ContentEditorForm.UpdateRibbon(Item folder, Boolean isCurrentItemChanged, Boolean showEditor) +502
>    Sitecore.Shell.Applications.ContentManager.ContentEditorForm.Update() +600
>    Sitecore.Shell.Applications.ContentManager.ContentEditorForm.OnPreRendered(EventArgs e) +172
> 
> [TargetInvocationException: Exception has been thrown by the target of an invocation.]
>    System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
>    System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
>    System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
>    Sitecore.Reflection.ReflectionUtil.InvokeMethod(MethodInfo method, Object[] parameters, Object obj) +89
>    Sitecore.Shell.Applications.ContentManager.ContentEditorPage.OnPreRender(EventArgs e) +143
>    System.Web.UI.Control.PreRenderRecursiveInternal() +107
>    System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +7675

 
Also raised this issue in stackoverflow.

http://sitecore.stackexchange.com/questions/5022/value-cannot-be-null-parameter-name-fieldnametranslator-opening-content-edit?noredirect=1#comment8050_5022

Any inputs would help, to find a way out, Appreciate your inputs.

**Comment by Sivalingaamorthy** [comment]
I found the solution, it  is because of mis-configuration.

http://sitecore.stackexchange.com/questions/5022/value-cannot-be-null-parameter-name-fieldnametranslator-opening-content-edit

**Comment by gunasekaransengodan** [comment]
I am using Sitecore 7.1 Update 3 with Solr 4.3.1 , Issue Still Exist. Given solution not solving.

Note: Not Error Log.

**Comment by senbagaraman04** [comment]
After installing some packages, I'm facing this error in Sitecore version 8.2 update 1. The solution which we found is stopping the IIS App Pool and starting them after 5 minutes, which is working till now.
